services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  ragbot:
    build: .
    ports:
      - "8080:8080"
      - "7860:7860"
    volumes:
      - ./docs:/app/docs
    depends_on:
      - qdrant
