version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEEPSEEK_API_KEY=
    volumes:
      - ./data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "7860:7860"
    depends_on:
      - backend

volumes:
  data: