services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    entrypoint: /bin/bash
    command: -c "ollama serve & until ollama list; do sleep 2; done && ollama pull mistral && wait"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ragnet
  chatbot:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    networks:
      - ragnet

networks:
  ragnet:
    driver: bridge

volumes:
  ollama_data:
